---
title: "Norwood GAM individual tag id"
author: "Hannah Barrett"
date: "2023-10-29"
output:

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
rm(list=ls())
library(survival)
library(ggplot2)
library(plotly)
library(ggpubr)
library(htmlwidgets)
library(reticulate)
library(viridis)
library(ggforce)
library(dplyr)
library(lubridate)
library(sjPlot)
library(AICcmodavg)
library(mgcv)
library(tidyverse)
library(rmarkdown)

setwd("C:/Users/barrehan/GitHub/projects/cwa.habitat.selection.dvm")
nor.ib<- read.csv("data/modif.data/hab.select.mod/norwood.ibutton.data/norwood.ibutton.pooled.csv")
nor.ib$date.time <- ymd_hms(nor.ib$date.time)
nor.ib <- nor.ib %>% force_tz(nor.ib$date.time, tzone = "America/Los_Angeles")
nor.ib<-nor.ib[nor.ib$date.time >="2021-07-30 00:00:00" & nor.ib$date.time < "2021-08-06 00:00:00",]

# Data frames by high/low interval ----------------------------------------

high.int <- nor.ib[nor.ib$highlowDO.2hours == "high",]
high.int <- high.int[!is.na(high.int$highlowDO.2hours),]

low.int <- nor.ib[nor.ib$highlowDO.2hours == "low",]
low.int <- low.int[!is.na(low.int$highlowDO.2hours),]


```

GAM Norwood high DO tag 2
```{r}

high.int.2 <-high.int[high.int$ibutton.id == 2,]
high.int.2$dumt <-rep(1,nrow(high.int.2))

gam.high.2<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM
             data = high.int.2,
             family=cox.ph, weights = case)
summary(gam.high.2)

pred.vals.high.2<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(high.int.2$standardized.temp, na.rm = T),
                                                           max(high.int.2$standardized.temp, na.rm = T),
                                                           0.1), stratID = 691)

preds.gam.high.2 <- predict.gam(gam.high.2, newdata = pred.vals.high.2, type = 'link', se.fit = T) 


preds.gam.high.2<-cbind(pred.vals.high.2, preds.gam.high.2)
preds.gam.high.2$lcl<-preds.gam.high.2$fit - (1.96*preds.gam.high.2$se.fit)
preds.gam.high.2$ucl<-preds.gam.high.2$fit + (1.96*preds.gam.high.2$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.high.2$temperature <- preds.gam.high.2$standardized.temp*sd.t+mean.t
preds.gam.high.2$dissolved.oxygen<-preds.gam.high.2$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.high.2, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.25, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.high.2 <-expand_grid(
  standardized.do = seq(from = min(high.int.2$standardized.do, na.rm = T), 
               to = max(high.int.2$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(high.int.2$standardized.temp, na.rm = T), 
                  to = max(high.int.2$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.high.2 <- predict(gam.high.2, newdata = df.pred.high.2,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.high.2)

# Back transform temp and do for plot

df.pred.high.2$temperature <- df.pred.high.2$standardized.temp*sd.t+mean.t
df.pred.high.2$dissolved.oxygen <-df.pred.high.2$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.high.2, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = high.int.2[high.int.2$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = high.int.2[high.int.2$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.high.2, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood low DO tag 2
```{r}

low.int.2 <-low.int[low.int$ibutton.id == 2,]
low.int.2$dumt <-rep(1,nrow(low.int.2))

gam.low.2<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.2,
             family=cox.ph, weights = case)
summary(gam.low.2)

pred.vals.low.2<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.2$standardized.temp, na.rm = T),
                                                           max(low.int.2$standardized.temp, na.rm = T),
                                                           0.1), stratID = 691)

preds.gam.low.2 <- predict.gam(gam.low.2, newdata = pred.vals.low.2, type = 'link', se.fit = T) 


preds.gam.low.2<-cbind(pred.vals.low.2, preds.gam.low.2)
preds.gam.low.2$lcl<-preds.gam.low.2$fit - (1.96*preds.gam.low.2$se.fit)
preds.gam.low.2$ucl<-preds.gam.low.2$fit + (1.96*preds.gam.low.2$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.2$temperature <- preds.gam.low.2$standardized.temp*sd.t+mean.t
preds.gam.low.2$dissolved.oxygen<-preds.gam.low.2$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.2, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.25, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.2 <-expand_grid(
  standardized.do = seq(from = min(low.int.2$standardized.do, na.rm = T), 
               to = max(low.int.2$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.2$standardized.temp, na.rm = T), 
                  to = max(low.int.2$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.2 <- predict(gam.low.2, newdata = df.pred.low.2,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.2)

# Back transform temp and do for plot

df.pred.low.2$temperature <- df.pred.low.2$standardized.temp*sd.t+mean.t
df.pred.low.2$dissolved.oxygen <-df.pred.low.2$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.2, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.2[low.int.2$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.2[low.int.2$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.2, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

<!-- GAM Norwood high DO tag 4 -->
<!-- ```{r} -->

<!-- high.int.4 <-high.int[high.int$ibutton.id == 4,] -->
<!-- high.int.4$dumt <-rep(1,nrow(high.int.4)) -->

<!-- gam.high.4<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM -->
<!--              data = high.int.4, -->
<!--              family=cox.ph, weights = case) -->
<!-- summary(gam.high.4) -->

<!-- pred.vals.high.4<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard -->
<!--                                    standardized.temp = seq(min(high.int.4$standardized.temp, na.rm = T), -->
<!--                                                            max(high.int.4$standardized.temp, na.rm = T), -->
<!--                                                            0.1), stratID = 2130) -->

<!-- preds.gam.high.4 <- predict.gam(gam.high.4, newdata = pred.vals.high.4, type = 'link', se.fit = T)  -->


<!-- preds.gam.high.4<-cbind(pred.vals.high.4, preds.gam.high.4) -->
<!-- preds.gam.high.4$lcl<-preds.gam.high.4$fit - (1.96*preds.gam.high.4$se.fit) -->
<!-- preds.gam.high.4$ucl<-preds.gam.high.4$fit + (1.96*preds.gam.high.4$se.fit) -->

<!-- #back transformation from standardized scale -->
<!-- mean.t<-mean(nor.ib$temperature) -->
<!-- sd.t <-sd(nor.ib$temperature) -->
<!-- mean.do<-mean(nor.ib$dissolved.oxygen) -->
<!-- sd.do<-sd(nor.ib$dissolved.oxygen) -->

<!-- preds.gam.high.4$temperature <- preds.gam.high.4$standardized.temp*sd.t+mean.t -->
<!-- preds.gam.high.4$dissolved.oxygen<-preds.gam.high.4$standardized.do*sd.do+mean.do -->

<!-- #Plot -->

<!-- ggplot(preds.gam.high.4, aes(x=temperature, y=fit)) + -->
<!--   geom_line(aes(y = fit), linewidth = 1.45, color = "#01353D")+ -->
<!--   geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+ -->
<!--   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), axis.line = element_line(colour = "black"), -->
<!--         text = element_text(size = 15, family = "serif"))+ -->
<!--   xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+ -->
<!--   theme(legend.title = element_blank()) -->

<!-- ######Contour Plot####### -->

<!-- #Prep -->

<!-- df.pred.high.4 <-expand_grid( -->
<!--   standardized.do = seq(from = min(high.int.4$standardized.do, na.rm = T),  -->
<!--                to = max(high.int.4$standardized.do, na.rm = T),  -->
<!--                length.out = 100), -->
<!--   standardized.temp = seq(from = min(high.int.4$standardized.temp, na.rm = T),  -->
<!--                   to = max(high.int.4$standardized.temp, na.rm = T),  -->
<!--                   length.out = 100) -->
<!-- ) -->

<!-- df.pred.high.4 <- predict(gam.high.4, newdata = df.pred.high.4, -->
<!--                         se.fit = T)%>% -->
<!--   as_tibble()%>% -->
<!--   cbind(df.pred.high.4) -->

<!-- # Back transform temp and do for plot -->

<!-- df.pred.high.4$temperature <- df.pred.high.4$standardized.temp*sd.t+mean.t -->
<!-- df.pred.high.4$dissolved.oxygen <-df.pred.high.4$standardized.do*sd.do+mean.do -->

<!-- #Plot -->

<!-- ggplot()+ -->
<!--   geom_tile(data = df.pred.high.4, aes(x = temperature, y = dissolved.oxygen, fill = fit))+ -->
<!--   geom_point(data = high.int.4[high.int.4$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+ -->
<!--   geom_point(data = high.int.4[high.int.4$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+ -->
<!--   scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+ -->
<!--   geom_contour(data = df.pred.high.4, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+ -->
<!--   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), axis.line = element_line(colour = "black"), -->
<!--         legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+ -->
<!--   xlab(label = "Temperature (\u00B0C)") + -->
<!--   ylab(label = "Dissolved oxygen (mg/l)")+ -->
<!--   labs(fill='')  -->

<!-- ``` -->

<!-- GAM Norwood low DO tag 4 -->
<!-- ```{r} -->

<!-- low.int.4 <-low.int[low.int$ibutton.id == 4,] -->
<!-- low.int.4$dumt <-rep(1,nrow(low.int.4)) -->

<!-- gam.low.4<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp),  -->
<!--              data = low.int.4, -->
<!--              family=cox.ph, weights = case) -->
<!-- summary(gam.low.4) -->

<!-- pred.vals.low.4<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard -->
<!--                                    standardized.temp = seq(min(low.int.4$standardized.temp, na.rm = T), -->
<!--                                                            max(low.int.4$standardized.temp, na.rm = T), -->
<!--                                                            0.1), stratID = 2130) -->

<!-- preds.gam.low.4 <- predict.gam(gam.low.4, newdata = pred.vals.low.4, type = 'link', se.fit = T)  -->


<!-- preds.gam.low.4<-cbind(pred.vals.low.4, preds.gam.low.4) -->
<!-- preds.gam.low.4$lcl<-preds.gam.low.4$fit - (1.96*preds.gam.low.4$se.fit) -->
<!-- preds.gam.low.4$ucl<-preds.gam.low.4$fit + (1.96*preds.gam.low.4$se.fit) -->

<!-- #back transformation from standardized scale -->
<!-- mean.t<-mean(nor.ib$temperature) -->
<!-- sd.t <-sd(nor.ib$temperature) -->
<!-- mean.do<-mean(nor.ib$dissolved.oxygen) -->
<!-- sd.do<-sd(nor.ib$dissolved.oxygen) -->

<!-- preds.gam.low.4$temperature <- preds.gam.low.4$standardized.temp*sd.t+mean.t -->
<!-- preds.gam.low.4$dissolved.oxygen<-preds.gam.low.4$standardized.do*sd.do+mean.do -->

<!-- #Plot -->

<!-- ggplot(preds.gam.low.4, aes(x=temperature, y=fit)) + -->
<!--   geom_line(aes(y = fit), linewidth = 1.25, color = "#01353D")+ -->
<!--   geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+ -->
<!--   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), axis.line = element_line(colour = "black"), -->
<!--         text = element_text(size = 15, family = "serif"))+ -->
<!--   xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+ -->
<!--   theme(legend.title = element_blank()) -->

<!-- ######Contour Plot####### -->

<!-- #Prep -->

<!-- df.pred.low.4 <-expand_grid( -->
<!--   standardized.do = seq(from = min(low.int.4$standardized.do, na.rm = T),  -->
<!--                to = max(low.int.4$standardized.do, na.rm = T),  -->
<!--                length.out = 100), -->
<!--   standardized.temp = seq(from = min(low.int.4$standardized.temp, na.rm = T),  -->
<!--                   to = max(low.int.4$standardized.temp, na.rm = T),  -->
<!--                   length.out = 100) -->
<!-- ) -->

<!-- df.pred.low.4 <- predict(gam.low.4, newdata = df.pred.low.4, -->
<!--                         se.fit = T)%>% -->
<!--   as_tibble()%>% -->
<!--   cbind(df.pred.low.4) -->

<!-- # Back transform temp and do for plot -->

<!-- df.pred.low.4$temperature <- df.pred.low.4$standardized.temp*sd.t+mean.t -->
<!-- df.pred.low.4$dissolved.oxygen <-df.pred.low.4$standardized.do*sd.do+mean.do -->

<!-- #Plot -->

<!-- ggplot()+ -->
<!--   geom_tile(data = df.pred.low.4, aes(x = temperature, y = dissolved.oxygen, fill = fit))+ -->
<!--   geom_point(data = low.int.4[low.int.4$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+ -->
<!--   geom_point(data = low.int.4[low.int.4$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+ -->
<!--   scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+ -->
<!--   geom_contour(data = df.pred.low.4, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+ -->
<!--   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), -->
<!--         panel.background = element_blank(), axis.line = element_line(colour = "black"), -->
<!--         legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+ -->
<!--   xlab(label = "Temperature (\u00B0C)") + -->
<!--   ylab(label = "Dissolved oxygen (mg/l)")+ -->
<!--   labs(fill='')  -->

<!-- ``` -->

GAM Norwood high DO tag 6
```{r}

high.int.6 <-high.int[high.int$ibutton.id == 6,]
high.int.6$dumt <-rep(1,nrow(high.int.6))

gam.high.6<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM
             data = high.int.6,
             family=cox.ph, weights = case)
summary(gam.high.6)

pred.vals.high.6<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(high.int.6$standardized.temp, na.rm = T),
                                                           max(high.int.6$standardized.temp, na.rm = T),
                                                           0.1), stratID = 3570)

preds.gam.high.6 <- predict.gam(gam.high.6, newdata = pred.vals.high.6, type = 'link', se.fit = T) 


preds.gam.high.6<-cbind(pred.vals.high.6, preds.gam.high.6)
preds.gam.high.6$lcl<-preds.gam.high.6$fit - (1.96*preds.gam.high.6$se.fit)
preds.gam.high.6$ucl<-preds.gam.high.6$fit + (1.96*preds.gam.high.6$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.high.6$temperature <- preds.gam.high.6$standardized.temp*sd.t+mean.t
preds.gam.high.6$dissolved.oxygen<-preds.gam.high.6$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.high.6, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.45, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.high.6 <-expand_grid(
  standardized.do = seq(from = min(high.int.6$standardized.do, na.rm = T), 
               to = max(high.int.6$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(high.int.6$standardized.temp, na.rm = T), 
                  to = max(high.int.6$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.high.6 <- predict(gam.high.6, newdata = df.pred.high.6,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.high.6)

# Back transform temp and do for plot

df.pred.high.6$temperature <- df.pred.high.6$standardized.temp*sd.t+mean.t
df.pred.high.6$dissolved.oxygen <-df.pred.high.6$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.high.6, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = high.int.6[high.int.6$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = high.int.6[high.int.6$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.high.6, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood low DO tag 6
```{r}

low.int.6 <-low.int[low.int$ibutton.id == 6,]
low.int.6$dumt <-rep(1,nrow(low.int.6))

gam.low.6<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.6,
             family=cox.ph, weights = case)
summary(gam.low.6)

pred.vals.low.6<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.6$standardized.temp, na.rm = T),
                                                           max(low.int.6$standardized.temp, na.rm = T),
                                                           0.1), stratID = 3570)

preds.gam.low.6 <- predict.gam(gam.low.6, newdata = pred.vals.low.6, type = 'link', se.fit = T) 


preds.gam.low.6<-cbind(pred.vals.low.6, preds.gam.low.6)
preds.gam.low.6$lcl<-preds.gam.low.6$fit - (1.96*preds.gam.low.6$se.fit)
preds.gam.low.6$ucl<-preds.gam.low.6$fit + (1.96*preds.gam.low.6$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.6$temperature <- preds.gam.low.6$standardized.temp*sd.t+mean.t
preds.gam.low.6$dissolved.oxygen<-preds.gam.low.6$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.6, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.65, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.6 <-expand_grid(
  standardized.do = seq(from = min(low.int.6$standardized.do, na.rm = T), 
               to = max(low.int.6$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.6$standardized.temp, na.rm = T), 
                  to = max(low.int.6$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.6 <- predict(gam.low.6, newdata = df.pred.low.6,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.6)

# Back transform temp and do for plot

df.pred.low.6$temperature <- df.pred.low.6$standardized.temp*sd.t+mean.t
df.pred.low.6$dissolved.oxygen <-df.pred.low.6$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.6, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.6[low.int.6$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.6[low.int.6$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.6, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood high DO tag 13
```{r}

high.int.13 <-high.int[high.int$ibutton.id == 13,]
high.int.13$dumt <-rep(1,nrow(high.int.13))

gam.high.13<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM
             data = high.int.13,
             family=cox.ph, weights = case)
summary(gam.high.13)

pred.vals.high.13<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(high.int.13$standardized.temp, na.rm = T),
                                                           max(high.int.13$standardized.temp, na.rm = T),
                                                           0.1), stratID = 5010)

preds.gam.high.13 <- predict.gam(gam.high.13, newdata = pred.vals.high.13, type = 'link', se.fit = T) 


preds.gam.high.13<-cbind(pred.vals.high.13, preds.gam.high.13)
preds.gam.high.13$lcl<-preds.gam.high.13$fit - (1.96*preds.gam.high.13$se.fit)
preds.gam.high.13$ucl<-preds.gam.high.13$fit + (1.96*preds.gam.high.13$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.high.13$temperature <- preds.gam.high.13$standardized.temp*sd.t+mean.t
preds.gam.high.13$dissolved.oxygen<-preds.gam.high.13$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.high.13, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.45, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.high.13 <-expand_grid(
  standardized.do = seq(from = min(high.int.13$standardized.do, na.rm = T), 
               to = max(high.int.13$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(high.int.13$standardized.temp, na.rm = T), 
                  to = max(high.int.13$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.high.13 <- predict(gam.high.13, newdata = df.pred.high.13,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.high.13)

# Back transform temp and do for plot

df.pred.high.13$temperature <- df.pred.high.13$standardized.temp*sd.t+mean.t
df.pred.high.13$dissolved.oxygen <-df.pred.high.13$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.high.13, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = high.int.13[high.int.13$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = high.int.13[high.int.13$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.high.13, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood low DO tag 13
```{r}

low.int.13 <-low.int[low.int$ibutton.id == 13,]
low.int.13$dumt <-rep(1,nrow(low.int.13))

gam.low.13<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.13,
             family=cox.ph, weights = case)
summary(gam.low.13)

pred.vals.low.13<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.13$standardized.temp, na.rm = T),
                                                           max(low.int.13$standardized.temp, na.rm = T),
                                                           0.1), stratID = 5010)

preds.gam.low.13 <- predict.gam(gam.low.13, newdata = pred.vals.low.13, type = 'link', se.fit = T) 


preds.gam.low.13<-cbind(pred.vals.low.13, preds.gam.low.13)
preds.gam.low.13$lcl<-preds.gam.low.13$fit - (1.96*preds.gam.low.13$se.fit)
preds.gam.low.13$ucl<-preds.gam.low.13$fit + (1.96*preds.gam.low.13$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.13$temperature <- preds.gam.low.13$standardized.temp*sd.t+mean.t
preds.gam.low.13$dissolved.oxygen<-preds.gam.low.13$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.13, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.135, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.13 <-expand_grid(
  standardized.do = seq(from = min(low.int.13$standardized.do, na.rm = T), 
               to = max(low.int.13$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.13$standardized.temp, na.rm = T), 
                  to = max(low.int.13$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.13 <- predict(gam.low.13, newdata = df.pred.low.13,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.13)

# Back transform temp and do for plot

df.pred.low.13$temperature <- df.pred.low.13$standardized.temp*sd.t+mean.t
df.pred.low.13$dissolved.oxygen <-df.pred.low.13$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.13, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.13[low.int.13$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.13[low.int.13$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.13, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood high DO tag 14
```{r}

high.int.14 <-high.int[high.int$ibutton.id == 14,]
high.int.14$dumt <-rep(1,nrow(high.int.14))

gam.high.14<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM
             data = high.int.14,
             family=cox.ph, weights = case)
summary(gam.high.14)

pred.vals.high.14<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(high.int.14$standardized.temp, na.rm = T),
                                                           max(high.int.14$standardized.temp, na.rm = T),
                                                           0.1), stratID = 6449)

preds.gam.high.14 <- predict.gam(gam.high.14, newdata = pred.vals.high.14, type = 'link', se.fit = T) 


preds.gam.high.14<-cbind(pred.vals.high.14, preds.gam.high.14)
preds.gam.high.14$lcl<-preds.gam.high.14$fit - (1.96*preds.gam.high.14$se.fit)
preds.gam.high.14$ucl<-preds.gam.high.14$fit + (1.96*preds.gam.high.14$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.high.14$temperature <- preds.gam.high.14$standardized.temp*sd.t+mean.t
preds.gam.high.14$dissolved.oxygen<-preds.gam.high.14$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.high.14, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.45, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.high.14 <-expand_grid(
  standardized.do = seq(from = min(high.int.14$standardized.do, na.rm = T), 
               to = max(high.int.14$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(high.int.14$standardized.temp, na.rm = T), 
                  to = max(high.int.14$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.high.14 <- predict(gam.high.14, newdata = df.pred.high.14,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.high.14)

# Back transform temp and do for plot

df.pred.high.14$temperature <- df.pred.high.14$standardized.temp*sd.t+mean.t
df.pred.high.14$dissolved.oxygen <-df.pred.high.14$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.high.14, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = high.int.14[high.int.14$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = high.int.14[high.int.14$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.high.14, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood low DO tag 14
```{r}

low.int.14 <-low.int[low.int$ibutton.id == 14,]
low.int.14$dumt <-rep(1,nrow(low.int.14))

gam.low.14<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.14,
             family=cox.ph, weights = case)
summary(gam.low.14)

pred.vals.low.14<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.14$standardized.temp, na.rm = T),
                                                           max(low.int.14$standardized.temp, na.rm = T),
                                                           0.1), stratID = 6449)

preds.gam.low.14 <- predict.gam(gam.low.14, newdata = pred.vals.low.14, type = 'link', se.fit = T) 


preds.gam.low.14<-cbind(pred.vals.low.14, preds.gam.low.14)
preds.gam.low.14$lcl<-preds.gam.low.14$fit - (1.96*preds.gam.low.14$se.fit)
preds.gam.low.14$ucl<-preds.gam.low.14$fit + (1.96*preds.gam.low.14$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.14$temperature <- preds.gam.low.14$standardized.temp*sd.t+mean.t
preds.gam.low.14$dissolved.oxygen<-preds.gam.low.14$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.14, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.145, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.14 <-expand_grid(
  standardized.do = seq(from = min(low.int.14$standardized.do, na.rm = T), 
               to = max(low.int.14$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.14$standardized.temp, na.rm = T), 
                  to = max(low.int.14$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.14 <- predict(gam.low.14, newdata = df.pred.low.14,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.14)

# Back transform temp and do for plot

df.pred.low.14$temperature <- df.pred.low.14$standardized.temp*sd.t+mean.t
df.pred.low.14$dissolved.oxygen <-df.pred.low.14$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.14, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.14[low.int.14$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.14[low.int.14$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.14, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood high DO tag 16
```{r}

high.int.16 <-high.int[high.int$ibutton.id == 16,]
high.int.16$dumt <-rep(1,nrow(high.int.16))

gam.high.16<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM
             data = high.int.16,
             family=cox.ph, weights = case)
summary(gam.high.16)

pred.vals.high.16<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(high.int.16$standardized.temp, na.rm = T),
                                                           max(high.int.16$standardized.temp, na.rm = T),
                                                           0.1), stratID = 7889)

preds.gam.high.16 <- predict.gam(gam.high.16, newdata = pred.vals.high.16, type = 'link', se.fit = T) 


preds.gam.high.16<-cbind(pred.vals.high.16, preds.gam.high.16)
preds.gam.high.16$lcl<-preds.gam.high.16$fit - (1.96*preds.gam.high.16$se.fit)
preds.gam.high.16$ucl<-preds.gam.high.16$fit + (1.96*preds.gam.high.16$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.high.16$temperature <- preds.gam.high.16$standardized.temp*sd.t+mean.t
preds.gam.high.16$dissolved.oxygen<-preds.gam.high.16$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.high.16, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.45, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.high.16 <-expand_grid(
  standardized.do = seq(from = min(high.int.16$standardized.do, na.rm = T), 
               to = max(high.int.16$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(high.int.16$standardized.temp, na.rm = T), 
                  to = max(high.int.16$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.high.16 <- predict(gam.high.16, newdata = df.pred.high.16,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.high.16)

# Back transform temp and do for plot

df.pred.high.16$temperature <- df.pred.high.16$standardized.temp*sd.t+mean.t
df.pred.high.16$dissolved.oxygen <-df.pred.high.16$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.high.16, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = high.int.16[high.int.16$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = high.int.16[high.int.16$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.high.16, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood low DO tag 16
```{r}

low.int.16 <-low.int[low.int$ibutton.id == 16,]
low.int.16$dumt <-rep(1,nrow(low.int.16))

gam.low.16<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.16,
             family=cox.ph, weights = case)
summary(gam.low.16)

pred.vals.low.16<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.16$standardized.temp, na.rm = T),
                                                           max(low.int.16$standardized.temp, na.rm = T),
                                                           0.1), stratID = 7889)

preds.gam.low.16 <- predict.gam(gam.low.16, newdata = pred.vals.low.16, type = 'link', se.fit = T) 


preds.gam.low.16<-cbind(pred.vals.low.16, preds.gam.low.16)
preds.gam.low.16$lcl<-preds.gam.low.16$fit - (1.96*preds.gam.low.16$se.fit)
preds.gam.low.16$ucl<-preds.gam.low.16$fit + (1.96*preds.gam.low.16$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.16$temperature <- preds.gam.low.16$standardized.temp*sd.t+mean.t
preds.gam.low.16$dissolved.oxygen<-preds.gam.low.16$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.16, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.165, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.16 <-expand_grid(
  standardized.do = seq(from = min(low.int.16$standardized.do, na.rm = T), 
               to = max(low.int.16$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.16$standardized.temp, na.rm = T), 
                  to = max(low.int.16$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.16 <- predict(gam.low.16, newdata = df.pred.low.16,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.16)

# Back transform temp and do for plot

df.pred.low.16$temperature <- df.pred.low.16$standardized.temp*sd.t+mean.t
df.pred.low.16$dissolved.oxygen <-df.pred.low.16$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.16, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.16[low.int.16$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.16[low.int.16$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.16, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```


GAM Norwood high DO tag 18
```{r}

high.int.18 <-high.int[high.int$ibutton.id == 18,]
high.int.18$dumt <-rep(1,nrow(high.int.18))

gam.high.18<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), #how to add interaction for GAM
             data = high.int.18,
             family=cox.ph, weights = case)
summary(gam.high.18)

pred.vals.high.18<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(high.int.18$standardized.temp, na.rm = T),
                                                           max(high.int.18$standardized.temp, na.rm = T),
                                                           0.1), stratID = 9329)

preds.gam.high.18 <- predict.gam(gam.high.18, newdata = pred.vals.high.18, type = 'link', se.fit = T) 


preds.gam.high.18<-cbind(pred.vals.high.18, preds.gam.high.18)
preds.gam.high.18$lcl<-preds.gam.high.18$fit - (1.96*preds.gam.high.18$se.fit)
preds.gam.high.18$ucl<-preds.gam.high.18$fit + (1.96*preds.gam.high.18$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.high.18$temperature <- preds.gam.high.18$standardized.temp*sd.t+mean.t
preds.gam.high.18$dissolved.oxygen<-preds.gam.high.18$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.high.18, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.45, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.high.18 <-expand_grid(
  standardized.do = seq(from = min(high.int.18$standardized.do, na.rm = T), 
               to = max(high.int.18$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(high.int.18$standardized.temp, na.rm = T), 
                  to = max(high.int.18$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.high.18 <- predict(gam.high.18, newdata = df.pred.high.18,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.high.18)

# Back transform temp and do for plot

df.pred.high.18$temperature <- df.pred.high.18$standardized.temp*sd.t+mean.t
df.pred.high.18$dissolved.oxygen <-df.pred.high.18$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.high.18, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = high.int.18[high.int.18$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = high.int.18[high.int.18$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.high.18, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

GAM Norwood low DO tag 18
```{r}

low.int.18 <-low.int[low.int$ibutton.id == 18,]
low.int.18$dumt <-rep(1,nrow(low.int.18))

gam.low.18<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.18,
             family=cox.ph, weights = case)
summary(gam.low.18)

pred.vals.low.18<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.18$standardized.temp, na.rm = T),
                                                           max(low.int.18$standardized.temp, na.rm = T),
                                                           0.1), stratID = 9329)

preds.gam.low.18 <- predict.gam(gam.low.18, newdata = pred.vals.low.18, type = 'link', se.fit = T) 


preds.gam.low.18<-cbind(pred.vals.low.18, preds.gam.low.18)
preds.gam.low.18$lcl<-preds.gam.low.18$fit - (1.96*preds.gam.low.18$se.fit)
preds.gam.low.18$ucl<-preds.gam.low.18$fit + (1.96*preds.gam.low.18$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.18$temperature <- preds.gam.low.18$standardized.temp*sd.t+mean.t
preds.gam.low.18$dissolved.oxygen<-preds.gam.low.18$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.18, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.185, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.18 <-expand_grid(
  standardized.do = seq(from = min(low.int.18$standardized.do, na.rm = T), 
               to = max(low.int.18$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.18$standardized.temp, na.rm = T), 
                  to = max(low.int.18$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.18 <- predict(gam.low.18, newdata = df.pred.low.18,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.18)

# Back transform temp and do for plot

df.pred.low.18$temperature <- df.pred.low.18$standardized.temp*sd.t+mean.t
df.pred.low.18$dissolved.oxygen <-df.pred.low.18$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.18, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.18[low.int.18$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.18[low.int.18$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.18, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```


GAM Norwood low DO tag 4
```{r}

low.int.4 <-low.int[low.int$ibutton.id == 4,]
low.int.4$dumt <-rep(1,nrow(low.int.4))

gam.low.4<-gam(cbind(dumt,stratID) ~ s(standardized.do,standardized.temp), 
             data = low.int.4,
             family=cox.ph, weights = case)
summary(gam.low.4)

pred.vals.low.4<- data.frame(standardized.do = -0.3603449, #setting DO to 4mg/l epa standard
                                   standardized.temp = seq(min(low.int.4$standardized.temp, na.rm = T),
                                                           max(low.int.4$standardized.temp, na.rm = T),
                                                           0.1), stratID = 2070)

preds.gam.low.4 <- predict.gam(gam.low.4, newdata = pred.vals.low.4, type = 'link', se.fit = T) 


preds.gam.low.4<-cbind(pred.vals.low.4, preds.gam.low.4)
preds.gam.low.4$lcl<-preds.gam.low.4$fit - (1.96*preds.gam.low.4$se.fit)
preds.gam.low.4$ucl<-preds.gam.low.4$fit + (1.96*preds.gam.low.4$se.fit)

#back transformation from standardized scale
mean.t<-mean(nor.ib$temperature)
sd.t <-sd(nor.ib$temperature)
mean.do<-mean(nor.ib$dissolved.oxygen)
sd.do<-sd(nor.ib$dissolved.oxygen)

preds.gam.low.4$temperature <- preds.gam.low.4$standardized.temp*sd.t+mean.t
preds.gam.low.4$dissolved.oxygen<-preds.gam.low.4$standardized.do*sd.do+mean.do

#Plot

ggplot(preds.gam.low.4, aes(x=temperature, y=fit)) +
  geom_line(aes(y = fit), linewidth = 1.25, color = "#01353D")+
  geom_ribbon(aes(ymin=lcl, ymax=ucl), alpha=0.2, fill="#01353D")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        text = element_text(size = 15, family = "serif"))+
  xlab("Temperature (\u00B0C)") + ylab("Relative probability of selection")+
  theme(legend.title = element_blank())

######Contour Plot#######

#Prep

df.pred.low.4 <-expand_grid(
  standardized.do = seq(from = min(low.int.4$standardized.do, na.rm = T), 
               to = max(low.int.4$standardized.do, na.rm = T), 
               length.out = 100),
  standardized.temp = seq(from = min(low.int.4$standardized.temp, na.rm = T), 
                  to = max(low.int.4$standardized.temp, na.rm = T), 
                  length.out = 100)
)

df.pred.low.4 <- predict(gam.low.4, newdata = df.pred.low.4,
                        se.fit = T)%>%
  as_tibble()%>%
  cbind(df.pred.low.4)

# Back transform temp and do for plot

df.pred.low.4$temperature <- df.pred.low.4$standardized.temp*sd.t+mean.t
df.pred.low.4$dissolved.oxygen <-df.pred.low.4$standardized.do*sd.do+mean.do

#Plot

ggplot()+
  geom_tile(data = df.pred.low.4, aes(x = temperature, y = dissolved.oxygen, fill = fit))+
  geom_point(data = low.int.4[low.int.4$case == 0,], aes(x = temperature, y = dissolved.oxygen), colour = "black", alpha = 0.5)+
  geom_point(data = low.int.4[low.int.4$case == 1,], aes(x = temperature, y = dissolved.oxygen), colour = "white", alpha = 0.75)+
  scale_fill_gradientn(colours = c("#D4D9DD", "#AEB2B7", "#878195", "#7C5467", "#532A34","#291919"))+
  geom_contour(data = df.pred.low.4, aes(x = temperature, y = dissolved.oxygen, z= fit), colour = "white")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        legend.key=element_rect(fill="white"), text = element_text(size = 15, family = "serif"))+
  xlab(label = "Temperature (\u00B0C)") +
  ylab(label = "Dissolved oxygen (mg/l)")+
  labs(fill='') 

```

